// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreManager.DAL.Infrastructure;

#nullable disable

namespace StoreManager.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("StoreManager.Models.Product", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Sku");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("StoreManager.Models.Stock", b =>
                {
                    b.Property<string>("ProductSku")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductSku", "StoreCode");

                    b.HasIndex("StoreCode");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("StoreManager.Models.Store", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("StoreManager.Models.Stock", b =>
                {
                    b.HasOne("StoreManager.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductSku")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreManager.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");
                });
#pragma warning restore 612, 618
        }
    }
}
